---
- name: Install UFW firewall
  package:
    name: ufw
    state: present
  become: yes

- name: Reset UFW to defaults
  ufw:
    state: reset
  become: yes

- name: Configure UFW default policies
  ufw:
    direction: "{{ item.direction }}"
    policy: "{{ item.policy }}"
  become: yes
  loop:
    - { direction: 'incoming', policy: "{{ ufw_defaults.incoming }}" }
    - { direction: 'outgoing', policy: "{{ ufw_defaults.outgoing }}" }
    - { direction: 'forward', policy: "{{ ufw_defaults.forward }}" }

- name: Configure UFW rules
  ufw:
    rule: "{{ item.rule }}"
    port: "{{ item.port | default(omit) }}"
    proto: "{{ item.proto | default(omit) }}"
    comment: "{{ item.comment | default(omit) }}"
  become: yes
  loop: "{{ ufw_rules }}"

- name: Enable UFW
  ufw:
    state: enabled
  become: yes

- name: Get UFW status
  command: ufw status verbose
  register: ufw_status
  become: yes
  changed_when: false

- name: Display UFW status
  debug:
    var: ufw_status.stdout_lines